#!/bin/bash

# if not possible to install venv or virtualenv already installed, use following command instad of apt-get and venv venv commands
# virtualenv -p `which python3` venv 
sudo apt-get install python3-venv
python3 -m venv venv
. venv/bin/activate
pip install configparser
pip install Flask
pip install mysql-connector-python
echo Finished
